import chalk from 'chalk';

export interface AnalysisResult {
  symbol: string;
  summary: string;
}

export function formatReportHeader(symbols: string[]): string {
  const timestamp = new Date().toISOString().replace('T', ' ').split('.')[0];
  return [
    chalk.bold.cyan('═'.repeat(60)),
    chalk.bold.white(`  Oak Invest Analysis Report`),
    chalk.gray(`  ${timestamp}`),
    chalk.bold.cyan('═'.repeat(60)),
    chalk.white(`  Analyzing: ${symbols.join(', ')}`),
    '',
  ].join('\n');
}

export function formatReportFooter(): string {
  return [
    '',
    chalk.bold.cyan('═'.repeat(60)),
    chalk.gray('  Report generated by oak-invest'),
    chalk.gray('  Following Howard Marks\' investment philosophy'),
    chalk.bold.cyan('═'.repeat(60)),
  ].join('\n');
}

export function streamToConsole(text: string): void {
  process.stdout.write(text);
}

export function formatStreamingReport(fullText: string): void {
  process.stdout.write('\n');
  process.stdout.write(fullText);
  process.stdout.write('\n');
}
